// <auto-generated />
using System;
using FaceLogin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaceLogin.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("FaceLogin.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameUser")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhotoUser")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Faces");
                });
#pragma warning restore 612, 618
        }
    }
}
